// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpkyJihqWnb_RxWDOe4tHJhT7VTMZa-Iw',
    appId: '1:334981123241:web:eced550c30fc9bfd03adb8',
    messagingSenderId: '334981123241',
    projectId: 'ukk-xii-pplg-1-2025-bren',
    authDomain: 'ukk-xii-pplg-1-2025-bren.firebaseapp.com',
    storageBucket: 'ukk-xii-pplg-1-2025-bren.firebasestorage.app',
    measurementId: 'G-BZQ7HD3311',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdbeSa_kAbz35ckUEnZgaS8uqWZ-iQHs',
    appId: '1:334981123241:android:301eb1f94a8eba5c03adb8',
    messagingSenderId: '334981123241',
    projectId: 'ukk-xii-pplg-1-2025-bren',
    storageBucket: 'ukk-xii-pplg-1-2025-bren.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjY52W_X-D83dxqowDB7uDcvZgf3d3uA',
    appId: '1:334981123241:ios:142fff61fb03ba3b03adb8',
    messagingSenderId: '334981123241',
    projectId: 'ukk-xii-pplg-1-2025-bren',
    storageBucket: 'ukk-xii-pplg-1-2025-bren.firebasestorage.app',
    iosBundleId: 'com.example.projectUkk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQjY52W_X-D83dxqowDB7uDcvZgf3d3uA',
    appId: '1:334981123241:ios:142fff61fb03ba3b03adb8',
    messagingSenderId: '334981123241',
    projectId: 'ukk-xii-pplg-1-2025-bren',
    storageBucket: 'ukk-xii-pplg-1-2025-bren.firebasestorage.app',
    iosBundleId: 'com.example.projectUkk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpkyJihqWnb_RxWDOe4tHJhT7VTMZa-Iw',
    appId: '1:334981123241:web:56c08dc3099862e903adb8',
    messagingSenderId: '334981123241',
    projectId: 'ukk-xii-pplg-1-2025-bren',
    authDomain: 'ukk-xii-pplg-1-2025-bren.firebaseapp.com',
    storageBucket: 'ukk-xii-pplg-1-2025-bren.firebasestorage.app',
    measurementId: 'G-JNE2DVXSFD',
  );

}